#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach",True)
#driver = webdriver.Chrome(opts)
#driver.get('https://demowebshop.tricentis.com/')
#driver.find_element("xpath","//a[@class='ico-register']").click()
#time.sleep(2)
#driver.find_element("xpath","//input[@id='gender-female']").click()
#time.sleep(2)
#driver.find_element("xpath","//input[@name='FirstName']").send_keys('Priya')
#time.sleep(1)
#driver.find_element("xpath","//input[@id='LastName']").send_keys('Vanaparthi')
#driver.find_element("xpath","//input[@name='Email']").send_keys('Priya526@gmail.com')
#driver.find_element("xpath","//input[@name='Password']").send_keys('Manunithya')
#driver.find_element("xpath","//input[@name='ConfirmPassword']").send_keys('Manunithya')
#driver.find_element("xpath","//input[@id='register-button']").click()
#driver.find_element("xpath","//a[@class='ico-logout']").click()
#driver.find_element("xpath","//a[@class='ico-login']").click()
#driver.find_element("xpath","//input[@id='Email']").send_keys('Priya526@gmail.com')
#driver.find_element("xpath","//input[@name='Password']").send_keys('Manunithya')
#driver.find_element("xpath","//input[@value='Log in']").click()
#driver.find_element("xpath","//a[@class='ico-logout']").click()

#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach",True)
#driver = webdriver.Chrome(opts)
#driver.get('https://www.amazon.in')
#time.sleep(2)
#driver.find_element("xpath",'''//a[text()="Today's Deals"]''').click()
#time.sleep(2)
#driver.find_element("xpath",'//button[text()="Coupons"]').click()
#time.sleep(2)
#driver.find_element("xpath",'//span[text()="Appliances"]').click()

#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach",True)
#driver = webdriver.Chrome(opts)
#driver.get('https://www.facebook.com/r.php?locale=en_GB&display=page')
#time.sleep(2)
#driver.find_element('xpath','(//input[@type="text"])[1]').send_keys('katrina')
#driver.find_element('xpath','(//input[@type="text"])[2]').send_keys('soppadandi')
#driver.find_element('xpath','(//input[@type="text"])[5]').send_keys('katrina@gmail.com')
#time.sleep(2)

#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach",True)
#driver = webdriver.Chrome(opts)
#driver.get('https://blinkit.com/')
#driver.find_element('xpath','//button[text()="Detect my location"]').click()
#time.sleep(2)
#driver.find_element('xpath','//div[text()="Login"]').click()
#time.sleep(2)
#driver.find_element('xpath','//input[@class="login-phone__input input"]').send_keys('9908431679')
#time.sleep(2)
#driver.find_element('xpath','//button[text()="Continue"]').click()
#time.sleep(2)

import time
from selenium import webdriver
opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach",True)
driver = webdriver.Chrome(opts)
driver.get('https://www.myntra.com')
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[1]').click()
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[2]').click()
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[3]').click()
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[4]').click()
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[5]').click()
time.sleep(2)
driver.find_element("xpath",'(//a[class="desktop-main"])[6]').click()
time.sleep(2)

#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach", True)
#driver = webdriver.Chrome(opts)
#driver.get('https://www.saucedemo.com/')
#time.sleep(2)
#driver.find_element('xpath', '//input[@id="user-name"]').send_keys('standard_user')
#time.sleep(1)
#driver.find_element('xpath', '//input[@id="password"]').send_keys('secret_sauce')
#time.sleep(1)
#driver.find_element('xpath', '//input[@id="login-button"]').click()
#time.sleep(3)
#driver.find_element('xpath', '//button[@id="react-burger-menu-btn"]').click()
#time.sleep(2)
#driver.find_element('xpath', '//a[@id="logout_sidebar_link"]').click()

#import time
#from selenium import webdriver
#opts = webdriver.ChromeOptions()
#opts.add_experimental_option("detach", True)
#driver = webdriver.Chrome(opts)
#driver.get('https://www.facebook.com/r.php?entry_point=login')
#time.sleep(2)
#driver.find_element('xpath', '//input[@name="firstname"]').send_keys('Harry')
#time.sleep(1)
#driver.find_element('xpath', '//input[@name="lastname"]').send_keys('Potter')
#time.sleep(1)
#driver.find_element('xpath', '//input[@name="reg_email__"]').send_keys('harry@gmail.com')
#time.sleep(1)
#driver.find_element('xpath', '//input[@name="reg_passwd__"]').send_keys('harry@12345')
