import time
from selenium import webdriver
opts = webdriver.ChromeOptions()
opts.add_experimental_option("detach",True)
driver = webdriver.Chrome(opts)
driver.get('https://www.amazon.com/')
time.sleep(2)
#driver.maximize_window()
time.sleep(2)
#driver.back()
time.sleep(2)
#driver.forward()
time.sleep(2)
#print(driver.title)
#print(driver.current_url)
#print(driver.page_source)
#print(driver.name)
driver.save_screenshot('amazon_loginpage.png')
driver.save_screenshot(r'C:\Users\91949\PycharmProjects\selenium_training\Files')
driver.close()
